spring.application.name=AppXtractBackend
app.base-url=${APPXTRACT_BASE_URL}

spring.datasource.url=jdbc:postgresql://${APPXTRACT_DB_HOST}:${APPXTRACT_DB_PORT}/${APPXTRACT_DB_NAME}
spring.datasource.username=${APPXTRACT_DB_USER}
spring.datasource.password=${APPXTRACT_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.max-file-size=50GB
spring.servlet.multipart.max-request-size=50GB

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#JWT Token Configuration
jwt.secret=${APPXTRACT_JWT_SECRET}
jwt.expiration.short=86400000
jwt.expiration.long=1209600000